baseURL = "https://kandaka.netlify.app/"
languageCode = "en-us"
title = "Kandaka"
theme = "ananke"

[params]
  description = "An Economics Development Website for Sudan"
  custom_css = ["ananke/css/custom.css"]
  show_reading_time = true